[package]
name = "math"
version = "0.1.0"
authors = ["Rafael Alcaraz Mercado <rafawo1@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde-serde = []

[dependencies]
num-traits = "0.2.14"
